import type { PluginMetadata } from "@/types/plugin";
import { createEntrySettings } from "@/libs/plugin-entry-settings";
import {
  DEFAULT_COVER_SOURCES,
  DEFAULT_SITE_CREDENTIALS,
  DEFAULT_TEMPLATES,
} from "./sources";

export const pluginMetadata: PluginMetadata = {
  name: "moreBackground",
  displayName: "lets-more-background.displayName",
  description: "lets-more-background.description",
  version: "1.0.0",
  enabled: false,
  icon: "image",
  settings: [
    ...createEntrySettings({ menu: true, tab: true }, { central: true }),
    {
      type: "number",
      title: "lets-more-background.widthTitle",
      description: "lets-more-background.widthDescription",
      key: "width",
      value: 1920,
    },
    {
      type: "number",
      title: "lets-more-background.heightTitle",
      description: "lets-more-background.heightDescription",
      key: "height",
      value: 1080,
    },
    {
      type: "textinput",
      title: "lets-more-background.assetsLocationTitle",
      description: "lets-more-background.assetsLocationDescription",
      key: "assetsLocation",
      value: "/assets/more-background",
    },
    {
      type: "checkbox",
      title: "lets-more-background.readFromAssetsTitle",
      description: "lets-more-background.readFromAssetsDescription",
      key: "readFromAssets",
      value: true,
    },
    {
      type: "checkbox",
      title: "lets-more-background.writeToAssetsTitle",
      description: "lets-more-background.writeToAssetsDescription",
      key: "writeToAssets",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-more-background.localCacheTitle",
      description: "lets-more-background.localCacheDescription",
      key: "localCache",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-more-background.autoCacheLegacyCoversTitle",
      description: "lets-more-background.autoCacheLegacyCoversDescription",
      key: "autoCacheLegacyCovers",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-more-background.purgeCacheOnCoverChangeTitle",
      description: "lets-more-background.purgeCacheOnCoverChangeDescription",
      key: "purgeCacheOnCoverChange",
      value: false,
    },
    {
      type: "textinput",
      title: "lets-more-background.localCacheRootTitle",
      description: "lets-more-background.localCacheRootDescription",
      key: "localCacheRoot",
      value: "/storage/petal/siyuan-damophus/more-background/covers",
    },
    {
      type: "textinput",
      title: "lets-more-background.localCachePathTemplateTitle",
      description: "lets-more-background.localCachePathTemplateDescription",
      key: "localCachePathTemplate",
      value: "{year}/{month}/{hash}.webp",
    },
    {
      type: "select",
      title: "lets-more-background.localCacheMaxEdgeTitle",
      description: "lets-more-background.localCacheMaxEdgeDescription",
      key: "localCacheMaxEdge",
      value: "1920",
      options: {
        none: "lets-more-background.localCacheMaxEdgeOriginal",
        "1280": "lets-more-background.localCacheMaxEdge1280",
        "1920": "lets-more-background.localCacheMaxEdge1920",
        "2560": "lets-more-background.localCacheMaxEdge2560",
      },
    },
    {
      type: "number",
      title: "lets-more-background.coverHistoryLimitTitle",
      description: "lets-more-background.coverHistoryLimitDescription",
      key: "coverHistoryLimit",
      value: 150,
    },
    {
      type: "number",
      title: "lets-more-background.coverSeenLimitTitle",
      description: "lets-more-background.coverSeenLimitDescription",
      key: "coverSeenLimit",
      value: 800,
    },
    {
      type: "checkbox",
      title: "lets-more-background.directDragTitle",
      description: "lets-more-background.directDragDescription",
      key: "directDrag",
      value: false,
    },
    {
      type: "select",
      title: "lets-more-background.toolbarPositionTitle",
      description: "lets-more-background.toolbarPositionDescription",
      key: "toolbarPosition",
      value: "belowIcon",
      options: {
        belowIcon: "lets-more-background.toolbarPositionBelowIcon",
        native: "lets-more-background.toolbarPositionNative",
        custom: "lets-more-background.toolbarPositionCustom",
      },
    },
    {
      type: "slider",
      title: "lets-more-background.toolbarCustomXTitle",
      description: "lets-more-background.toolbarCustomXDescription",
      key: "toolbarCustomX",
      value: 50,
      slider: { min: 0, max: 100, step: 1 },
    },
    {
      type: "slider",
      title: "lets-more-background.toolbarCustomYTitle",
      description: "lets-more-background.toolbarCustomYDescription",
      key: "toolbarCustomY",
      value: 15,
      slider: { min: 0, max: 100, step: 1 },
    },
    {
      type: "checkbox",
      title: "lets-more-background.coverBreadcrumbTitle",
      description: "lets-more-background.coverBreadcrumbDescription",
      key: "coverBreadcrumb",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-more-background.coverDocumentMenuTitle",
      description: "lets-more-background.coverDocumentMenuDescription",
      key: "coverDocumentMenu",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-more-background.confirmRemoveCoverTitle",
      description: "lets-more-background.confirmRemoveCoverDescription",
      key: "confirmRemoveCover",
      value: true,
    },
    {
      type: "list",
      title: "lets-more-background.credentialsTab",
      description: "lets-more-background.credentialsDescription",
      key: "siteCredentials",
      value: DEFAULT_SITE_CREDENTIALS,
    },
    {
      type: "list",
      title: "lets-more-background.templatesTab",
      description: "lets-more-background.templatesTab",
      key: "templates",
      value: DEFAULT_TEMPLATES,
    },
    {
      type: "list",
      title: "lets-more-background.sourcesTitle",
      description: "lets-more-background.sourcesDescription",
      key: "sources",
      value: DEFAULT_COVER_SOURCES,
    },
  ],
};

export default pluginMetadata;
