packages:
  - '.'
  - 'packages/*'

allowBuilds:
  "@parcel/watcher": true
  "core-js": true
  "es5-ext": true
  "esbuild": true
  "@ibm/plex": true
  "@iflow-ai/iflow-cli": true
  "node-pty": true
  "opencode-ai": true
  "sharp": true

patchedDependencies:
  svelte-querybuilder: patches/svelte-querybuilder.patch
