import path, { resolve } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";
import minimist from "minimist";
import { viteStaticCopy } from "vite-plugin-static-copy";
import livereload from "rollup-plugin-livereload";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import tailwindcss from "@tailwindcss/vite";
import zipPack from "vite-plugin-zip-pack";
import fg from "fast-glob";
import fs from "node:fs";
import esbuild from "esbuild";

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

function loadTsFile(filePath: string) {
  const result = esbuild.buildSync({
    entryPoints: [filePath],
    bundle: true,
    write: false,
    format: "cjs",
    platform: "node",
  });
  const code = result.outputFiles[0].text;
  const m = { exports: {} as any };
  const fn = new Function("module", "exports", "require", "__dirname", "__filename", code);
  fn(m, m.exports, require, path.dirname(filePath), filePath);
  return m.exports;
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) {
      return;
    }
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

async function generateTranslations() {
  const partsDir = resolve(rootDir, "src/translations/parts");
  if (!fs.existsSync(partsDir)) {
    fs.mkdirSync(partsDir, { recursive: true });
  }

  const files = await fg("src/translations/parts/*.ts");
  
  const enImports = files.map((f, i) => `import { en as part${i} } from "./parts/${path.basename(f, ".ts")}";`).join("\n");
  const enSpreads = files.map((_, i) => `  ...part${i},`).join("\n");
  const enCode = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
${enImports}

export const en = {
${enSpreads}
};
`;
  writeIfChanged(resolve(rootDir, "src/translations/en.ts"), enCode);

  const zhImports = files.map((f, i) => `import { zhCN as part${i} } from "./parts/${path.basename(f, ".ts")}";`).join("\n");
  const zhSpreads = files.map((_, i) => `  ...part${i},`).join("\n");
  const zhCode = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
import { en } from "./en";
${zhImports}

export const zhCN: typeof en = {
${zhSpreads}
};
`;
  writeIfChanged(resolve(rootDir, "src/translations/zh-CN.ts"), zhCode);
  console.log("--> [i18n] Autogenerated en.ts and zh-CN.ts files (if changed).");
}

const args = minimist(process.argv.slice(2));
const isWatch = args.watch || args.w || false;
// const devDistDir = "./dev"
const devDistDir = "/Users/hqweay/SiYuan/data/plugins/siyuan-damophus";
const distDir = isWatch ? devDistDir : "./dist";

const watchExternalPlugin: Plugin = {
  name: "watch-external",
  async buildStart() {
    const files = await fg([
      "public/i18n/**",
      "src/translations/**",
      "./README*.md",
      "./plugin.json",
    ]);
    for (const file of files) {
      this.addWatchFile(file);
    }
  },
};

console.log("isWatch=>", isWatch);
console.log("distDir=>", distDir);

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(rootDir, "src"),
    },
  },

  plugins: [
    tailwindcss(),
    svelte({
      compilerOptions: {
        compatibility: {
          componentApi: 4,
        },
      },
    }),
    {
      name: "i18n-generate",
      async buildStart() {
        // 1. 扫描 parts 自动构建主入口 TS 文件
        await generateTranslations();

        // 2. 利用 esbuild 在内存中秒级编译并运行 TS，规避 Node.js 对 .ts 扩展名的加载限制
        const { en } = loadTsFile(resolve(rootDir, "src/translations/en.ts"));
        const { zhCN } = loadTsFile(resolve(rootDir, "src/translations/zh-CN.ts"));

        const i18nDir = resolve(rootDir, "public/i18n");
        if (!fs.existsSync(i18nDir)) {
          fs.mkdirSync(i18nDir, { recursive: true });
        }
        writeIfChanged(
          resolve(i18nDir, "zh-CN.json"),
          JSON.stringify(zhCN, null, 2)
        );
        writeIfChanged(
          resolve(i18nDir, "en.json"),
          JSON.stringify(en, null, 2)
        );
        console.log("--> [i18n] Generated JSON files from TS definitions (if changed).");
      },
    },

    viteStaticCopy({
      targets: [
        {
          src: "./README*.md",
          dest: "./",
        },
        {
          src: "./plugin.json",
          dest: "./",
        },
        {
          src: "./preview.png",
          dest: "./",
        },
        {
          src: "./icon.png",
          dest: "./",
        },
      ],
    }),
  ],

  // https://github.com/vitejs/vite/issues/1930
  // https://vitejs.dev/guide/env-and-mode.html#env-files
  // https://github.com/vitejs/vite/discussions/3058#discussioncomment-2115319
  // 在这里自定义变量
  define: {
    "process.env.DEV_MODE": `"${isWatch}"`,
    "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
  },

  build: {
    // 输出路径
    outDir: distDir,
    emptyOutDir: !isWatch,

    // 构建后是否生成 source map 文件
    sourcemap: false,

    // 设置为 false 可以禁用最小化混淆
    // 或是用来指定是应用哪种混淆器
    // boolean | 'terser' | 'esbuild'
    // 不压缩，用于调试
    minify: !isWatch,

    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(rootDir, "src/index.ts"),
      // the proper extensions will be added
      fileName: "index",
      formats: ["cjs"],
    },
    rollupOptions: {
      plugins: [
        ...(isWatch
          ? [
              livereload({
                watch: devDistDir,
                clientUrl: "http://localhost:35729/livereload.js?snipver=1",
              }),
              watchExternalPlugin,
            ]
          : [
              zipPack({
                inDir: "./dist",
                outDir: "./",
                outFileName: "package.zip",
              }),
            ]),
      ],

      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: ["siyuan", "process", "electron", "@electron/remote"],

      output: {
        entryFileNames: "[name].js",
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === "style.css") {
            return "index.css";
          }
          return assetInfo.name ?? "asset";
        },
      },
    },
  },
});
