<script lang="ts">
  import {
    BookA,
    BookOpenCheck,
    Bot,
    Boxes,
    Brain,
    CloudCog,
    FileOutput,
    Film,
    GlassWater,
    Globe2,
    GraduationCap,
    GripVertical,
    Highlighter,
    Image,
    ImagePlay,
    Images,
    LayoutGrid,
    ListTree,
    MessageSquareText,
    Move,
    Network,
    Paintbrush,
    Palette,
    PanelRight,
    Plug,
    Power,
    Settings2,
    Smartphone,
    Sparkles,
    SunMoon,
    TableProperties,
    Tags,
    TextSelect,
    Waypoints,
    Workflow,
  } from "lucide-svelte";
  import type { PluginIconName } from "@/libs/plugin-icons";

  export let name: PluginIconName;
  export let className = "size-4";

  const ICONS = {
    bookA: BookA,
    bookOpenCheck: BookOpenCheck,
    bot: Bot,
    boxes: Boxes,
    brain: Brain,
    cloudCog: CloudCog,
    fileOutput: FileOutput,
    film: Film,
    glassWater: GlassWater,
    globe2: Globe2,
    graduationCap: GraduationCap,
    gripVertical: GripVertical,
    highlighter: Highlighter,
    image: Image,
    imagePlay: ImagePlay,
    images: Images,
    layoutGrid: LayoutGrid,
    listTree: ListTree,
    messageSquareText: MessageSquareText,
    move: Move,
    network: Network,
    paintbrush: Paintbrush,
    palette: Palette,
    panelRight: PanelRight,
    plug: Plug,
    power: Power,
    settings: Settings2,
    smartphone: Smartphone,
    sparkles: Sparkles,
    sunMoon: SunMoon,
    tableProperties: TableProperties,
    tags: Tags,
    textSelect: TextSelect,
    waypoints: Waypoints,
    workflow: Workflow,
  } satisfies Record<PluginIconName, typeof Brain>;

  $: Icon = ICONS[name];
</script>

<svelte:component this={Icon} class={className} aria-hidden="true" />
